version = 0.1
[personal]

[personal.global.parameters]
stack_name = "andreadiotalleviart"
region = "eu-west-2"

[personal.sync.parameters]
profile = "personal"

[personal.logs.parameters]
profile = "personal"
