AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for andreadiotalleviart.com

Globals:
    Function:
        CodeUri: ./
        Timeout: 100
        Runtime: nodejs16.x
        MemorySize: 1024
        Tracing: Active
        Architectures:
            - x86_64

Resources:
    ApiGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            Cors:
                AllowMethods: "'*'"
                AllowHeaders: "'content-type, authorization'"
                AllowOrigin: "'*'"

    EventBus:
        Type: "AWS::Events::EventBus"
        Properties:
            Name: EventBus

    CreateCheckoutSessionFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${AWS::StackName}-CreateCheckoutSession
            Handler: src/handlers/createCheckoutSession.handler
            Events:
                Root:
                    Type: Api
                    Properties:
                        RestApiId: !Ref ApiGateway
                        Path: /create-checkout-session
                        Method: POST
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - src/handlers/createCheckoutSession.ts

    # WebhookFunction:
    #     Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    #     # DependsOn: WebhookSecretsManager
    #     Properties:
    #         FunctionName: !Sub [
    #                 "InboundWebhook-Lambda-${ID}",
    #                 ID: !Select [2, !Split ["/", !Ref AWS::StackId]],
    #             ] # Append the stack UUID
    #         CodeUri:
    #             Bucket: !Sub "eventbridge-inbound-webhook-templates-prod-${AWS::Region}"
    #             Key: "lambda-templates/stripe-lambdasrc.zip"
    #         Handler: app.lambda_handler
    #         Environment:
    #             Variables:
    #                 STRIPE_WEBHOOK_SECRET_ARN: !Ref WebhookSecretsManager
    #                 EVENT_BUS_NAME: !Ref EventBusName
    #         FunctionUrlConfig:
    #             AuthType: NONE
    #         # Policies:
    #         #     - EventBridgePutEventsPolicy:
    #         #         EventBusName: !Ref EventBusName
    #         #     - Version: "2012-10-17"
    #         #     Statement:
    #         #         - Effect: Allow
    #         #             Action:
    #         #                 - secretsmanager:DescribeSecret
    #         #                 - secretsmanager:GetSecretValue
    #         #             Resource: !Ref WebhookSecretsManager
