AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for andreadiotalleviart.com

Globals:
    Function:
        CodeUri: ./
        Timeout: 100
        Runtime: nodejs20.x
        MemorySize: 1024
        Tracing: Active
        Architectures:
            - x86_64

Resources:
    ApiGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            Auth:
                ApiKeyRequired: false
            Cors:
                AllowMethods: "'*'"
                AllowHeaders: "'Content-Type, Authorization, X-Api-Key'"
                AllowOrigin: "'*'"

    EventBus:
        Type: AWS::Events::EventBus
        Properties:
            Name: !Sub ${AWS::StackName}-EventBus

    EventBusRuleCheckoutSessionCompleted:
        Type: AWS::Events::Rule
        Properties:
            Name: CheckoutSessionCompleted
            EventBusName: !Ref EventBus
            EventPattern:
                source:
                    - "stripe"
                detailType:
                    - "CheckoutSessionCompleted"
            Targets:
                - Arn: !GetAtt CheckoutSessionCompletedSendEmailQueue.Arn
                  Id: TestId

    CheckoutSessionCompletedSendEmailQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: !Sub ${AWS::StackName}-CheckoutSessionCompletedSendEmailQueue
            VisibilityTimeout: 100

    CheckoutSessionCompletedEmailTemplate:
        Type: AWS::SES::Template
        Properties:
            Template:
                TemplateName: CheckoutSessionCompletedEmailTemplate
                HtmlPart: !Sub |
                    <html>
                        <body>
                            <h2>Thanks for your order {{name}}!</h2>
                            <p>As soon as your package is on its way, you will receive a delivery confirmation from me by email.</p>
                            <h3>Delivery address</h3>
                            <div>
                                {{fullName}}<br>
                                {{addressLine1}}<br>
                                {{addressLine2}}<br>
                                {{postcode}}, {{town}}, {{country}}
                            </div>
                            <h3>Your items</h3>
                            <div>
                                <article>
                                    Flames fine art print<br>
                                    Dimensions: 30x30 cm<br>
                                    Quantity: 1<br><br>
                                    <img src="https://www.andreadiotalleviart.com/moonlight.png" alt="Print thumbnail" width="120" height="120">
                                </article>
                            </div>
                            <h3>Payment summary</h3>
                            <details>
                                Payment method: {{paymentMethod}}<br>
                                Subtotal: £99.00<br>
                                Shipping fee: Free<br>
                                Discounts: £0.00<br>
                                Total: £99.00
                            </details>
                            <h3>With love, Andrea</h3>
                            <a href="https://andreadiotalleviart.com/shop">www.andreadiotalleviart.com</a>
                        </body>
                    </html>
                SubjectPart: "Your Andrea Diotallevi Art Order 2"

    CreateCheckoutSessionFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${AWS::StackName}-CreateCheckoutSession
            Handler: src/handlers/createCheckoutSession.handler
            Events:
                Root:
                    Type: Api
                    Properties:
                        RestApiId: !Ref ApiGateway
                        Path: /create-checkout-session
                        Method: POST
            Policies:
                - Statement:
                      - Sid: readParameterStore
                        Effect: Allow
                        Action:
                            - ssm:GetParameter
                        Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/STRIPE_SECRET_KEY
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - src/handlers/createCheckoutSession.ts

    RetrieveCheckoutSessionFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${AWS::StackName}-RetrieveCheckoutSession
            Handler: src/handlers/retrieveCheckoutSession.handler
            Events:
                Root:
                    Type: Api
                    Properties:
                        RestApiId: !Ref ApiGateway
                        Path: /retrieve-checkout-session/{sessionId}
                        Method: GET
            Policies:
                - Statement:
                      - Sid: readParameterStore
                        Effect: Allow
                        Action:
                            - ssm:GetParameter
                        Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/STRIPE_SECRET_KEY
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - src/handlers/retrieveCheckoutSession.ts

    SendEmailFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${AWS::StackName}-SendEmail
            Handler: src/handlers/sendEmail.handler
            Events:
                Root:
                    Type: Api
                    Properties:
                        RestApiId: !Ref ApiGateway
                        Path: /send-email
                        Method: POST
                MySQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt CheckoutSessionCompletedSendEmailQueue.Arn
                        BatchSize: 5
            Policies:
                - Statement:
                      - Sid: sendEmail
                        Effect: Allow
                        Action:
                            - ses:SendEmail
                            - ses:SendTemplatedEmail
                        Resource: "*"
                - Statement:
                      - Sid: readParameterStore
                        Effect: Allow
                        Action:
                            - ssm:GetParameter
                        Resource:
                            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/EMAIL_SOURCE
                            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/EMAIL_DESTINATION
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - src/handlers/sendEmail.ts

    StripeWebhookFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${AWS::StackName}-StripeWebhook
            Handler: src/handlers/stripeWebhook.handler
            Environment:
                Variables:
                    EVENT_BUS_NAME: !Ref EventBus
            Events:
                StripeWebhook:
                    Type: Api
                    Properties:
                        RestApiId: !Ref ApiGateway
                        Path: /stripe-webhook
                        Method: POST
            Policies:
                - Statement:
                      - Sid: readParameterStore
                        Effect: Allow
                        Action:
                            - ssm:GetParameter
                        Resource:
                            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/STRIPE_SECRET_KEY
                            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/STRIPE_SIGNING_SECRET
                - Statement:
                      - Sid: putEvents
                        Effect: Allow
                        Action:
                            - events:PutEvents
                        Resource: !GetAtt EventBus.Arn
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - src/handlers/stripeWebhook.ts
