AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for andreadiotalleviart.com

Globals:
    Function:
        CodeUri: ./
        Timeout: 100
        Runtime: nodejs20.x
        MemorySize: 1024
        Tracing: Active
        Architectures:
            - x86_64

Resources:
    ApiGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            Auth:
                AddApiKeyRequiredToCorsPreflight: false
                ApiKeyRequired: true
                UsagePlan:
                    CreateUsagePlan: PER_API
                    Description: Usage plan for this API
            Cors:
                AllowMethods: "'*'"
                AllowHeaders: "'Content-Type, Authorization, X-Api-Key'"
                AllowOrigin: "'*'"

    EventBus:
        Type: AWS::Events::EventBus
        Properties:
            Name: EventBus

    CheckoutSessionCompletedEmailTemplate:
        Type: AWS::SES::Template
        Properties:
            Template:
                TemplateName: CheckoutSessionCompletedEmailTemplate
                HtmlPart: !Sub |
                    <html>
                        <body>
                            <h2>Thanks for your order {{name}}!</h2>
                            <p>As soon as your package is on its way, you will receive a delivery confirmation from me by email.</p>
                            <h3>Delivery address</h3>
                            <div>
                                {{fullName}}<br>
                                {{addressLine1}}<br>
                                {{addressLine2}}<br>
                                {{postcode}}, {{town}}, {{country}}
                            </div>
                            <h3>Your items</h3>
                            <div>
                                <article>
                                    Flames fine art print<br>
                                    Dimensions: 30x30 cm<br>
                                    Quantity: 1<br><br>
                                    <img src="https://www.andreadiotalleviart.com/moonlight.png" alt="Print thumbnail" width="120" height="120">
                                </article>
                            </div>
                            <h3>Payment summary</h3>
                            <details>
                                Payment method: {{paymentMethod}}<br>
                                Subtotal: £99.00<br>
                                Shipping fee: Free<br>
                                Discounts: £0.00<br>
                                Total: £99.00
                            </details>
                            <h3>With love, Andrea</h3>
                            <a href="https://andreadiotalleviart.com/shop">www.andreadiotalleviart.com</a>
                        </body>
                    </html>
                SubjectPart: "Your Andrea Diotallevi Art Order 2"

    CreateCheckoutSessionFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${AWS::StackName}-CreateCheckoutSession
            Handler: src/handlers/createCheckoutSession.handler
            Events:
                Root:
                    Type: Api
                    Properties:
                        RestApiId: !Ref ApiGateway
                        Path: /create-checkout-session
                        Method: POST
            Policies:
                - Statement:
                      - Sid: readParameterStore
                        Effect: Allow
                        Action:
                            - ssm:GetParameter
                        Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/STRIPE_SECRET_KEY
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - src/handlers/createCheckoutSession.ts

    SendEmailFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub ${AWS::StackName}-SendEmail
            Handler: src/handlers/sendEmail.handler
            Events:
                Root:
                    Type: Api
                    Properties:
                        RestApiId: !Ref ApiGateway
                        Path: /send-email
                        Method: POST
            Policies:
                - Statement:
                      - Sid: sendEmail
                        Effect: Allow
                        Action:
                            - ses:SendEmail
                            - ses:SendTemplatedEmail
                        Resource: "*"
                - Statement:
                      - Sid: readParameterStore
                        Effect: Allow
                        Action:
                            - ssm:GetParameter
                        Resource:
                            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/EMAIL_SOURCE
                            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/EMAIL_DESTINATION
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - src/handlers/sendEmail.ts

    StripeWebhookFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        # DependsOn: WebhookSecretsManager
        Properties:
            FunctionName: Test
            # FunctionName: !Sub [
            #         "InboundWebhook-Lambda-${ID}",
            #         ID: !Select [2, !Split ["/", !Ref AWS::StackId]],
            #     ] # Append the stack UUID
            # CodeUri:
            #     Bucket: !Sub "eventbridge-inbound-webhook-templates-prod-${AWS::Region}"
            #     Key: "lambda-templates/stripe-lambdasrc.zip"
            Handler: src/handlers/stripeWebhook.handler
            # Environment:
            #     Variables:
            #         STRIPE_WEBHOOK_SECRET_ARN: !Ref WebhookSecretsManager
            #         EVENT_BUS_NAME: !Ref EventBusName
            FunctionUrlConfig:
                AuthType: NONE
            # Policies:
            #     - EventBridgePutEventsPolicy:
            #         EventBusName: !Ref EventBusName
            #     - Version: "2012-10-17"
            #     Statement:
            #         - Effect: Allow
            #             Action:
            #                 - secretsmanager:DescribeSecret
            #                 - secretsmanager:GetSecretValue
            #             Resource: !Ref WebhookSecretsManager
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - src/handlers/stripeWebhook.ts
